### ISSUE TITLE
Dynamic queues

### ISSUE THREAD

**Issue by lrascao** [jlouis/safetyvalve#4]
Right now, all queue definitions must be present at sys.config on startup, it would be interesting to allow for dynamic spawning of additional parameterized queues. A typical use-case would be rate limiting certain operations on a per-user basis instead of system wide
i'm available for implementing said feature if deemed interesting for the project.

**Comment by jlouis** [comment]
I agree we should consider dynamic installation of queues. Things to think about:

* What happens if you reinstall a queue that is already there?
* What happens if you name the same queue, but with differing load rules? This would drive an eventual dampening under load. But what are the rules if you have a queue of size, K and you dampen its size to be less than K?
* What would the quickcheck model look like?

I'd say, come up with a rough API first, then try to implement it and adjust it as we go along whenever something doesn't add up.

**Comment by lrascao** [comment]
My ideia for the API would basically consist of a sv:new/2, sv:new/1 method which would create a named (arity 2, name and conf) or anonymous (arity 1, just conf) queue, in both cases it would return a pid. The rest of the API would remain retro-compatible due to the fact that gen_server:call accepts both names and pids. 
For named queues the same restrictions would apply as they do currently, ie. no two queues with the same name. You can have as many anonymous queues as desired, the invoker just needs to keep the pid and make all api invocations using it instead of the name.
I'm unfamiliar with quickcheck so i don't have any input regarding that, i'd be happy to look into it however

**Comment by jlouis** [comment]
This sound reasonable. Followup questions:

* How do you get rid of a dynamic queue?
* Can you change e.g., the concurrency level and/or queue size dynamically on an existing queue?
* Is the sv:new/X api idempotent?

I'll probably handle the QuickCheck stuff later :)

**Comment by lrascao** [comment]
* How do you get rid of a dynamic queue?
Good point, we'll probably need a destroy primitive also (destroy? kill? naming...), both the new and destroy of dynamic queues will be based on a simple_one_for_one supervisor with transient restart strategy, supervisor:start_child/terminate_child are the most obvious candidates

* Can you change e.g., the concurrency level and/or queue size dynamically on an existing queue?
I had thought about it, but i was trying to keep this feature contained just to the dynamic aspect of queue creation and leave queue reconfiguring to a separate PR

* Is the sv:new/X api idempotent?
only new/1 (the one that creates anonymous queues) is, new/2 fails the second time since it registers a named process

**Comment by lrascao** [comment]
One thing that has me worried though, is what could be a very intensive use of the timer wheel. Won't using several hundreds of thousands of safetyvalve queues (say one for each user) put a lot of stress on the timer wheel? at least in your experience..

**Comment by jlouis** [comment]
One thing I'd like to throw out is the idea that if you have a queue `Name` with configuration `Conf`, then issuing

        ok = sv:new(Name, Conf).

is a no-op, i.e., idempotent. Then, if a subsystem crashes but tries to recreate the queue, it will be able to do so without having to code for it, i.e., check for existence. Of course, if you try with `Conf2 /= Conf` then it will fail with an error case. It will remove lots of irritating code for users of the API.

As for the timer wheel: yes, it is a worry. The right solution nowadays is to adopt 18.0's new Timer API and forget about it, since it provides proper non-locking timer wheels. There are so timing-related things I'd like to fix in the current implementation because it is not distribution-safe. Taking the time outside the process and injecting it doesn't work if the caller is on a different node.

**Comment by lrascao** [comment]
Idempotent sv:new operation is indeed a useful operation, if you have no further remarks i'll incorporate what we discussed into a PR so we can move with a working basis

**Comment by lrascao** [comment]
Regarding the idempotency of new/X method, would it be acceptable to have only Name as the key? That is to say, in the example you provided earlier, if `Conf2 /= Conf`then new would be successful and return the pid of the first invocation.

**Comment by jlouis** [comment]
I'd test the configuration as well, simply because it can uncover bugs via crashing. I think this is enough for a useful PR.

**Comment by lrascao** [comment]
ok, this however means that upon invoking `supervisor:start_child` and determining the process is already running a request must be made for it's current configuration to be able to perform the comparison with the provided one, is this solution acceptable?

**Comment by jlouis** [comment]
I think so. It only ought to handle upon startup of a subsystem in most cases.

**Comment by jlouis** [comment]
Fixed by #6
